# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Shapfile AddEditInfo & rename
# "for" loop
# ListDatasets.py
# AddField.py
# Calculated.py
# Rename.py
# Created on: 2021-04-09 11:14:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

# Set path.
path = "D:\\ArcMap test\\State\\"

# Make country to a list.
file_L = os.listdir(path)

# Use "For Loop" run all the country under list path file.
for country_in_lower in file_L:
    # country title Upper.
    country_name = country_in_lower.title()
    print(country_name)
    arcpy.env.workspace = path + country_in_lower + "\\"

    # Until "work_File" is "Get all Shp. file under this path."
    # After "if" is "Set AddField."
    datasets1 = arcpy.ListDatasets(feature_type='feature')
    datasets2 = [''] + datasets1 if datasets1 is not None else []

    for ds in datasets2:
        for fc in arcpy.ListFeatureClasses(feature_dataset=ds):
            work_F = os.path.join(arcpy.env.workspace, ds, fc)           
            if arcpy.Exists(work_F):
                # Field title named "country"
                arcpy.AddField_management(work_F, "country", "TEXT", "", "",  75, "", "NULLABLE")
                # Calculated name is "country name" which is same file country name. Notice "quotation mark" !!!
                arcpy.CalculateField_management(work_F, "country", '"' + country_name + '"' , "PYTHON", "")
                print country_name + "_" + fc + " fields are added."
    
    #rename Shp.
    in_data_railway = "railway.shp"
    out_data_railway = country_name + "_railway.shp"

    in_data_road = "road.shp"
    out_data_road = country_name + "_road.shp"

    data_type = "FeatureClass"

    arcpy.Rename_management(in_data_railway, out_data_railway, data_type)
    arcpy.Rename_management(in_data_road, out_data_road, data_type)
    print country_name + " railway and road are renamed."   

print "Finished."
