# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ListDatasets.py
# AddField.py
# Created on: 2021-02-17 10:20:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

# Set path
arcpy.env.workspace = "D:\\ArcMap test\\SP\\"

# Until "Workfile" is "Get all Shp. file under this path."
# After "in_features" is "Set AddField."
datasets = arcpy.ListDatasets(feature_type='feature')
datasets = [''] + datasets if datasets is not None else []

for ds in datasets:
    for fc in arcpy.ListFeatureClasses(feature_dataset=ds):
        Workfile = os.path.join(arcpy.env.workspace, ds, fc)
        in_features = Workfile
        if arcpy.Exists(in_features):
            arcpy.AddField_management(in_features, "E_NAME", "TEXT", "", "",  10, "", "NULLABLE")
            print fc + " fields are added."
        
print "Finished."
