# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Make Feature Layer.py
# Select Layer By Attribute.py
# Delete Rows.py
# Created on: 2021-05-20 13:30:24.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Set path.
arcpy.env.workspace = "D:\\ArcMap test\\SelectDeleteRow.gdb\\"
arcpy.env.overwriteOutput = True

# Select layer in GDB.
layer_name = "railway_delete_try"

# Select table by SQL.
select_content = "country in ('Konigsberg', 'Stuttgart')"

# Make a temporary feature layer, select layer, and delete select rows.
arcpy.MakeFeatureLayer_management(layer_name, "railway_delete_try_layer")
arcpy.SelectLayerByAttribute_management("railway_delete_try_layer", "NEW_SELECTION", select_content)
arcpy.DeleteRows_management("railway_delete_try_layer")

print "Finishfd."
