# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Shapfile to Geodatabase by "For" loop
# ListDatasets.py
# FeatureClassToGeodatabase.py
# Created on: 2021-04-14 11:59:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

# Use "For Loop" run all the location under list path file.
path = "D:\\ArcMap test\\State\\"
file_l = os.listdir(path)

for shpfile in file_l:
    arcpy.env.workspace = path + shpfile + "\\"

    # To get all shp in file path.
    datasets1 = arcpy.ListDatasets(feature_type='feature')
    datasets2 = [''] + datasets1 if datasets1 is not None else []

    for ds in datasets2:
        for fc in arcpy.ListFeatureClasses(feature_dataset=ds):
            work_f = os.path.join(arcpy.env.workspace, ds, fc)

            # Set local variables
            out_location = "D:\\ArcMap test\\Country.gdb\\"
            arcpy.FeatureClassToGeodatabase_conversion(work_f, out_location)

print "Finished."
