# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Shapfile AddEditInfo & rename
# ListDatasets.py
# AddField.py
# Calculated.py
# Rename.py
# Created on: 2021-04-13 17:54:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Set environment settings
arcpy.env.workspace = "D:\\ArcMap test\\State\\Stuttgart\\"

# Set local variables
in_features = ['Stuttgart_railway.shp', 'Stuttgart_road.shp']
out_location = "D:\\ArcMap test\\State\\Country.gdb\\"

arcpy.FeatureClassToGeodatabase_conversion(in_features, out_location)
print "Finished."
