# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SimplifyPolygon.py for in gdb
# Created on: 2021-02-05 09:42:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
import arcpy.cartography as CA

# Set local variables
data_path = "D:\\ArcMap test\\try_in.gdb\\"
target_path = "D:\\ArcMap test\\try_out.gdb\\"

FEATURE_LIST = ["Kanshon", "Pintung"]

# Simplify Polygon
for fc in FEATURE_LIST:
    in_feature = data_path + fc
    out_feature = target_path + fc + "_SP"
    if arcpy.Exists(in_feature):
        CA.SimplifyPolygon(in_feature, out_feature, "POINT_REMOVE", 10, 0, "NO_CHECK", "KEEP_COLLAPSED_POINTS")
        print fc + "is SP"

print "Finished."
