# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SimplifyPolygon.py
# Created on: 2021-02-05 09:42:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
import arcpy.cartography as CA

# Set local variables
datafrom = "D:\\ArcMap test\\in_try\\Kanshon.shp"
datato = "D:\\ArcMap test\\out_try\\Try_SSP.shp"

# Simplify Polygon
CA.SimplifyPolygon(datafrom, datato, "POINT_REMOVE", 10, 0, "NO_CHECK", "KEEP_COLLAPSED_POINTS")

print "Finished."
