# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# clip.py
# Created on: 2017-02-21 09:42:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Local variables:
path = "D:\\ArcMap test\\SP\\"

main = '順向坡_'
fi_name = '.shp'

FEATURE_LIST = [main + "宜蘭" + fi_name, main + "花蓮" + fi_name, main + "南投" + fi_name, main + "屏東" + fi_name,\
                    main + "苗栗" + fi_name, main + "桃園" + fi_name, main + "高雄" + fi_name, main + "基隆" + fi_name,\
                    main + "雲林" + fi_name, main + "新北" + fi_name, main + "新竹" + fi_name, main + "嘉義" + fi_name,\
                    main + "彰化" + fi_name, main + "臺中" + fi_name, main + "臺北" + fi_name, main + "臺東" + fi_name,\
                    main + "臺南" + fi_name]

for fc in FEATURE_LIST:
     in_features = path + fc 
     if arcpy.Exists(in_features):
          arcpy.AddField_management(in_features, "C_NAME", "TEXT", "", "",  10, "", "NULLABLE")
          print fc + " fields are added."
         
 
print "Finished."
