# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SimplifyPolygon.py for in gdb
# Created on: 2021-02-05 09:42:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
import arcpy.cartography as CA

# Set local variables
data_path = "D:\\ArcMap test\\in_try\\"
simplify_path = "D:\\ArcMap test\\out_try\\"

FEATURE_LIST = ["Kanshon.shp", "Pintung.shp"]

# Simplify Polygon
for fc in FEATURE_LIST:
    in_feature = data_path + fc
    out_feature = simplify_path + fc
    if arcpy.Exists(in_feature):
        CA.SimplifyPolygon(in_feature, out_feature, "POINT_REMOVE", 10, 0, "NO_CHECK", "KEEP_COLLAPSED_POINTS")
        print fc + " is SP"

print "Finished."
